#!/usr/bin/env bash

if [[ $1 == "--audio" ]]; then
    extra_args="--extract-audio --audio-format mp3"
    shift 1
fi

if [[ $# -eq 0 ]]; then
    echo "you need to provide an argument"
    exit 1
fi

# only one file - output directly to stdout
if [[ $# -eq 1 ]]; then
    yt-dlp $extra_args -q -o - "$@"
    exit 0
fi

# multiple files - download all, zip and output to stdout
tmpdir=$(mktemp -d)

yt-dlp $extra_args -q -o "$tmpdir/%(title)s.%(ext)s" "$@"
zip -j -r - $tmpdir/* 2>/dev/null
